#ifndef UGPLUGIN_XBRAIDFORUG4_CONFIG_COMPILE_SETTINGS_HPP
#define UGPLUGIN_XBRAIDFORUG4_CONFIG_COMPILE_SETTINGS_HPP

#define WRITE_SCRIPT 1
#define SEND_RECV_TIMES 0
#define ExtendedInfo 0
#define FEATURE_SPATIAL_REFINE 1

#endif